---
title: "Tutorial"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

## Linux

### Quiz 1

Some questions to help you decide if your linux command-line skills are such that you  are ready for the RNAseq course:

```{r quiz}
quiz(
    question("Choose the correct Unix command used for this task - Copy a file ",
    answer("mv"),
    answer("cd"),
    answer("cp", correct = TRUE),
    answer("copyfile"),
    answer("copy")
  ),
        question("Choose the correct Unix command used for this task - Print the current directory ",
    answer("mv"),
    answer("cd"),
    answer("cp"),
    answer("copyfile"),
    answer("pwd", correct = TRUE)
  ),
  question("Which package contains functions for installing other R packages?",
    answer("base"),
    answer("tools"),
    answer("utils", correct = TRUE),
    answer("codetools")
  ),
  question("Which of the R packages listed below are used to create plots?",
    answer("lattice", correct = TRUE),
    answer("tools"),
    answer("stats"),
    answer("grid", correct = TRUE)
  )
)
```
## R & Tidyverse

### Quiz 2

Some further questions to help you decide if your R and Tidyverse skills are such that you  are ready for the RNAseq course:
